### ISSUE TITLE
Error with installation : permission denied

### ISSUE THREAD

**Issue by daweth** [transmissions11/forgeup#1]
when running install command
I get ```bash: line 31: /usr/local/bin/forgeup: Permission denied```

**Comment by transmissions11** [comment]
yeah ur not root on your machine, im a bash noob so idk how to solve heh— if you've got ideas feel free to PR

**Comment by transmissions11** [comment]
maybe try 

```
curl https://raw.githubusercontent.com/transmissions11/forgeup/main/install > forgeup.sh
sudo bash forgeup.sh
```

**Comment by transmissions11** [comment]
if that works ill add to the readme

**Comment by ayushm2003** [comment]
was facing the same issue (using WSL). here's what I did -

`sudo touch forgeup.sh` (inside ` /usr/local/bin/`)
`sudo chown -R <username> forgeup.sh` (gives writing permission)

copy the executable and paste it in `forgeup.sh` using text editor
`sudo bash ./forgeup.sh`

**Comment by onbjerg** [comment]
> maybe try
> 
> ```
> curl https://raw.githubusercontent.com/transmissions11/forgeup/main/install > forgeup.sh
> sudo bash forgeup.sh
> ```

can just do `curl https://raw.githubusercontent.com/transmissions11/forgeup/main/install | sudo bash` that's what I do

**Comment by transmissions11** [comment]
i heard that didnt work for some folks but glad it did for you

**Comment by daweth** [comment]
I just ran `sudo install.sh` after cloning the repo locally. Idk what the bash version of this is but it worked

**Comment by transmissions11** [comment]
this should fix https://github.com/transmissions11/forgeup/pull/4
